
### Teste de buscar todos os pagamentos a receber
GET http://localhost:40000/getAllPaymentsToReceive HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTcxNjgwMzYsImV4cCI6MTY5NzE2ODYzNn0.f9DObjBzWaSly6HkCc-L3OCwrOwlQzOnb2EKctlzTcw

{

}

### Teste de buscar pagamento a receber por ID
POST http://localhost:40000/getPaymentToReceiveByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjk3MjA3MzQ0LCJleHAiOjE2OTcyMDc5NDR9.D1tcI2Uyy3ICvmBKmE06pnDE4Ynq8yZieQTh3dyaecU

{    
    "id": 1
}

### Teste de inserção de pagamento a receber
POST http://localhost:40000/insertPaymentsToReceive HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTcxNjgwMzYsImV4cCI6MTY5NzE2ODYzNn0.f9DObjBzWaSly6HkCc-L3OCwrOwlQzOnb2EKctlzTcw

{    
    "description": "Teste insert",
    "amount": 10.5,
    "due_date": "2023-10-15",
    "removed": false    
}

### Teste de atualização de pagamento a receber
POST http://localhost:40000/updatePaymentsToReceive HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTcxNjgwMzYsImV4cCI6MTY5NzE2ODYzNn0.f9DObjBzWaSly6HkCc-L3OCwrOwlQzOnb2EKctlzTcw

{       
    "id": 3,
    "description": "Teste update 3",
    "amount": 50.5,
    "due_date": "2023-10-18",
    "removed": false   
}

### teste de deleção de pagamento a receber
POST http://localhost:40000/deletePaymentsToReceive HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpYXQiOjE2OTcxNjgwMzYsImV4cCI6MTY5NzE2ODYzNn0.f9DObjBzWaSly6HkCc-L3OCwrOwlQzOnb2EKctlzTcw

{    
    "id": 5
}
