
### Teste de buscar todas as contas a pagar
GET http://localhost:40000/getAllBillsToPay HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNjk5NDYzNDA0LCJleHAiOjE2OTk0NjQwMDR9.UOnAdQjiRSoDsXf7icacJJ6mCq4KMrUiht-SnlG4mV4

{

}

### Teste de buscar conta a pagar por ID
POST http://localhost:40000/getBillToPayByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNjk5NDYzNDA0LCJleHAiOjE2OTk0NjQwMDR9.UOnAdQjiRSoDsXf7icacJJ6mCq4KMrUiht-SnlG4mV4

{    
    "id": 1
}

### Teste de inserção de conta a pagar
POST http://localhost:40000/insertBillsToPay HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNjk5NDYzNDA0LCJleHAiOjE2OTk0NjQwMDR9.UOnAdQjiRSoDsXf7icacJJ6mCq4KMrUiht-SnlG4mV4

{    
    "description": "Teste insert",
    "amount": 10.5,
    "due_date": "2023-10-15",
    "removed": false    
}

### Teste de atualização de conta a pagar
POST http://localhost:40000/updateBillsToPay HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNjk5NDYzNDA0LCJleHAiOjE2OTk0NjQwMDR9.UOnAdQjiRSoDsXf7icacJJ6mCq4KMrUiht-SnlG4mV4

{       
    "id": 3,
    "description": "Teste update 3",
    "amount": 50.5,
    "due_date": "2023-10-18",
    "removed": false   
}

### teste de deleção de conta a pagar
POST http://localhost:40000/deleteBillsToPay HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNjk5NDYzNDA0LCJleHAiOjE2OTk0NjQwMDR9.UOnAdQjiRSoDsXf7icacJJ6mCq4KMrUiht-SnlG4mV4

{    
    "id": 5
}
